[PR 2:5] feat: reader and writer components
NovoNordisk-OpenSource/decentralized-tech-radar pull request #31
Opened 2024-03-14 09:37 UTC by Slug-Boi

This PR includes the reader that takes a CSV file in and puts values into GO structs this allows the writer component to create a basic HTML page that has the blips listed. 
You can use the -file flag to specify a path to a .csv file
Resolves #20 
Resolves #19

2024-03-30 17:15 UTC, lasselundstenjensen requested changes
Fix the changes proposed in the comments before this PR can be approved.

2024-03-30 17:15 UTC, lasselundstenjensen commented on go.mod
>  module github.com/Agile-Arch-Angels/decentralized-tech-radar_dev
Module is pointing to your fork. Please change it and update the PR.

2024-03-30 17:15 UTC, lasselundstenjensen commented on src/View/html_test.go
> +	Reader "github.com/Agile-Arch-Angels/decentralized-tech-radar_dev/src/SpecReader"
Again, pointing to your fork. Please change it and update your PR.

2024-03-30 17:15 UTC, lasselundstenjensen commented on src/View/makeHtml.go
> +	Reader "github.com/Agile-Arch-Angels/decentralized-tech-radar_dev/src/SpecReader"
Again, this is pointing to your fork. Please change it and update your PR.

2024-03-30 17:15 UTC, lasselundstenjensen commented on src/main.go
> +	"github.com/Agile-Arch-Angels/decentralized-tech-radar_dev/src/SpecReader"
This dependency is pointing to your fork. Please change it and update the PR.

2024-03-30 17:15 UTC, lasselundstenjensen commented on docs/user_docs/temp
Empty file. Remove it or put a comment in it, if it is supposed to be there.
If you want the folder to remain, use a `.gitkeep` file instead.

2024-03-30 17:15 UTC, lasselundstenjensen commented on LICENSE
You should not be pushing a change to the license if your fork is up to date. It feels like your fork is behind or out of sync?

2024-03-30 17:15 UTC, lasselundstenjensen commented on .gitignore
Add `go.work.sum` to the `.gitignore` file.

2024-04-04 09:41 UTC, Slug-Boi commented on LICENSE
I had synced the fork way back and for some reason I guess the change only got caught on this PR? Well either way it is up to date now and should be good for the future PR's :shrug:

2024-04-04 10:03 UTC, zqueamish commented
We should now have resolved all comments. The only thing left is resolving the merge conflicts, which we have chosen to leave alone for now, and wait for further instructions:)

2024-04-08 06:53 UTC, zqueamish commented
The sync issues between this branch and the main are too severe, and as such we are not able to merge the two. We have incorporated the changes ((https://github.com/NovoNordisk-OpenSource/decentralized-tech-radar/pull/31#pullrequestreview-1970024636)) in later branches, so they will show up, and can seen through those. As such, we want to request to close this PR:)

2024-04-09 07:44 UTC, August-Brandt commented
> Module is pointing to your fork. Please change it and update the PR.  

Everywhere the module is pointing to the fork is being changed in PR #49
<br>

> Empty file. Remove it or put a comment in it, if it is supposed to be there. If you want the folder to remain, use a .gitkeep file instead.

This file is no longer exists because of the sync issue
<br>

> Add go.work.sum to the .gitignore file.  

The `go.work.sum` is bring added to the `.gitignore` in PR #73

2024-04-09 07:44 UTC, closed without merging